insert into dbo.Animals (Nume, Varsta) values
('Caine','Junior'),
('Caine','Senior'),
('Caine','Toate varstele'),
('Pisica','Junior'),
('Pisica','Senior'),
('Pisica','Toate varstele'),
('Iepure','Junior'),
('Iepure','Senior'),
('Iepure','Toate varstele'),
('Peste','Junior'),
('Peste','Senior'),
('Peste','Toate varstele'),
('Hamster','Junior'),
('Hamster','Senior'),
('Hamster','Toate varstele'),
('Papagal','Junior'),
('Papagal','Senior'),
('Papagal','Toate varstele');